### ISSUE TITLE
Deltas should maybe be more careful

### ISSUE THREAD

**Issue by bkardell** [bkardell/bcd-watch#10]
[This change](https://github.com/mdn/browser-compat-data/pull/22535/files) wound up showing as a bunch of changes in the support for the feed which is obviously not really the case and feels bad to me.

I also noticed that we're covering API and a lot of the stuff in there (all of it?) is about extensions. I wonder if that should be just filtered out or it's own feed or what? Thoughts @meyerweb ?

**Comment by meyerweb** [comment]
Definitely shouldn’t pick up changes of URL as changes in support.  As for API, I feel like we should leave in webextensions for the time being, but I could easily be overlooking something(s).  Is there a strong reason to split them off to their own thing?

**Comment by bkardell** [comment]
I wasn't intending on it, but I believe that #21 should fix this as well?
