### ISSUE TITLE
Add implementation information to `feature.addedImplementations`

### ISSUE THREAD

**Issue by meyerweb** [bkardell/bcd-watch#3]
At the moment, while the JS produces an array list that corresponds to the number of implementations that were added, those array entries don’t (seem to) contain the actual engines that have the new implementations.  It should at least include the names of the engines, and possibly also the version number (in case experimental builds and release builds show up without distinction).

**Comment by bkardell** [comment]
no version number, but the added implementations are now listed (it'll show up on the next run unless we want to go back and back-run a few (probably I will - but I thought maybe you should have a poke at whether you want to make other formatting changes first or else I'll have to do it again), but we can call this done.
