### ISSUE TITLE
Feature request: copyable BCD keys

### ISSUE THREAD

**Issue by ddbeck** [bkardell/bcd-watch#36]
Right now, features are shown with a pretty formatting, as in `api ➞ HTMLBaseElement ➞ href ➞ forbid_special_characters`. This is fine for reading.

But sometimes I see a key or group of keys that inspires me to author a feature in web-features. I'd like to copy those items into a web-features YAML file, or use a script to find the data in BCD. In those cases, I'd prefer to have the dot notation conventional to BCD and web-features, such as `api.HTMLBaseElement.href.forbid_special_characters`.

Thanks for considering this!

**Comment by bkardell** [comment]
So they'd be like this, effectively? 

<img width="874" alt="Screenshot 2024-07-11 at 11 56 16 AM" src="https://github.com/bkardell/bcd-watch/assets/870501/4f652a2c-9629-4494-a0b6-610b08a376dd">

**Comment by bkardell** [comment]
Just to clarify - I posted this mainly because it was easy to querySelector/replace and then have a 1:1 to say "so these are the values you'd want copyable" rather than "this is how we'd display them"... I'm not sure how I feel about the later, but ... yeah, what do you think?

**Comment by ddbeck** [comment]
Yeah, I should distinguish a bit here: it'd be nice if I could easily _copy_ text in the form `css.properties.position-try-fallbacks.none`, regardless of the presentation. I don't have an opinion on how it ought to look.

**Comment by bkardell** [comment]
Ok, we're seriously considering doing this - but we're thinking it probably would be confusing to most people, so we've been discussing ways to let some people uncover more -- like maybe let you give a hash argument on the URL or something to indicate you actually want that.  Anyway, it dawned on me that you _could_ also just make a bookmarklet...

```
javascript:(function()%7Bdocument.querySelectorAll('a%5Bhref%5D').forEach(it%20%3D%3E%20%7B%0A%20%20%20%20it.innerHTML%20%3D%20it.innerHTML.replaceAll('%20%E2%9E%9E%20'%2C%20'.')%0A%7D)%7D)()%3B
```

**Comment by bkardell** [comment]
After some further discussion, @meyerweb and I believe that perhaps a bookmark solution, works pretty well for this and won't confuse anyone, so closing this as wontfix (for now) and providing 
<a href="javascript:(function()%7Bdocument.querySelectorAll('li').forEach(it%20%3D%3E%20%7B%0A%20%20%20%20it.innerHTML%20%3D%20it.innerHTML.replaceAll('%20%E2%9E%9E%20'%2C%20'.')%0A%7D)%7D)()%3B">the bookmark</a> 
 solution you can save

**Comment by ddbeck** [comment]
Thank you!
