### ISSUE TITLE
Backfilled entries are missing some info

### ISSUE THREAD

**Issue by stof** [bkardell/bcd-watch#74]
The table of backfilled entries of the full report has a column saying `Backfilled from` for all rows of the table:
![image](https://github.com/user-attachments/assets/543d897a-4ec9-4b08-babd-bd3a3d1b92b7)

The markup for that is actually `Backfilled from <strong></strong>`. The presence of this empty `<strong>` tag makes me think that the column is expected to contain additional details (potentially different for each entry) that does not get rendered properly.

**Comment by meyerweb** [comment]
Thanks for the report!  This should be fixed now, both going forward and for all past entries.
